import Link from 'next/link';
import { ArrowRight, Bot, ChartNoAxesCombined, CheckCircle2, LockKeyhole, Radar, ShieldCheck } from 'lucide-react';

const modules = [
  ['暴露面检测', '用只读请求检查 HTTPS、TLS、响应头、Cookie 与基础配置，给出可复核的证据。', Radar],
  ['风险解释与整改', '将技术信号转成清晰的影响说明、优先级和修复建议，帮助团队快速行动。', Bot],
  ['持续安全指标', '登录后绑定站点，每日复测并记录评分、风险数量和整改后的变化趋势。', ChartNoAxesCombined],
];
export default function SolutionsPage() { return <main className="min-h-screen px-6 py-8"><div className="mx-auto max-w-6xl"><header className="flex items-center justify-between"><Link href="/" className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-5 w-5 text-cyan-300" />安盾云检</Link><div className="flex gap-3"><Link href="/login" className="btn-secondary px-4 py-2 text-sm">登录</Link><Link href="/register" className="btn-primary px-4 py-2 text-sm">开始使用</Link></div></header><section className="py-24 lg:grid lg:grid-cols-[1fr_0.8fr] lg:gap-16 lg:items-center"><div><div className="text-xs uppercase tracking-[0.28em] text-cyan-300/70">SECURITY GOVERNANCE, MADE CLEAR</div><h1 className="mt-5 max-w-3xl text-4xl font-bold leading-tight md:text-6xl">为没有专职安全团队的站点，建立一套可持续的安全判断。</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-400">安盾云检将规则检测、风险解释、AI 辅助报告和每日复测整合到一个控制台。它不做攻击，只帮助你确认自己负责的网站哪里需要加固。</p><Link href="/dashboard" className="btn-primary mt-8">立即检测<ArrowRight className="ml-2 h-4 w-4" /></Link></div><div className="glass-card mt-12 p-6 lg:mt-0"><div className="flex items-center gap-3 border-b border-white/10 pb-4"><LockKeyhole className="h-5 w-5 text-cyan-300" /><span className="font-semibold">一个完整的治理闭环</span></div><div className="mt-5 space-y-4">{['提交授权站点', '逐项检查安全信号', '查看风险优先级', '生成 AI 解释报告', '每日复测并观察趋势'].map((item, index) => <div key={item} className="flex items-center gap-3 text-sm text-slate-300"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-cyan-400/10 text-cyan-300">{index + 1}</span>{item}<CheckCircle2 className="ml-auto h-4 w-4 text-emerald-400" /></div>)}</div></div></section><section className="grid gap-5 border-t border-white/10 pt-12 md:grid-cols-3">{modules.map(([title, description, Icon]) => <article key={title as string} className="glass-card p-6"><Icon className="h-6 w-6 text-cyan-300" /><h2 className="mt-5 text-xl font-semibold">{title as string}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{description as string}</p></article>)}</section></div></main>; }
